language: ruby
rvm:
- 2.0.0
- 2.1.8
- 2.2.0
notifications:
  slack:
    secure: 1qR/3+riGv1Hgo2pO0YDp38lxsqfyEv8EpeNg+AuZrHsE++156gbbVz+B8ykZ7KtMzxBZSL6MkrLgWjkdQU3w/MxFWXrmAG+njnGyLCEOD8fgRBMZz7sgSNPZwVnPdYX3+y1B3kNIUV8xMBBs3BhlJyn14P/bT6JFrMAr/nndx/ygvdS9RzT8X77/urqSqBfOoTz47M0wor9Q9/4r7P+UpeswZyhcVkO35S6M1STiLwj7Ab/ZHVCCPboQInGv34ER9h0Vhs27Q1OeBNryveIJOZq12D+kLY/p3E/T6rjLH/abw1pLP2P3NCcyvSju2n38vF+uecbaSMlsZb804bpiCN47RWbJHUWs1iAXY7eemQBeFu7kr0xg5NUi/2KmfGyPM2XaRNHwHJ8IjXrid2XelDANOsXjZZ4JH1QGJ23zPy0vuMFV5IHA2msxnp3JOzA6WuWVU0a0atLhGSEGkjIPykWoU8rBNtRvEozEDmAVvYbP0/xYwahMLHtovxQuTNAZRUrJTBY+rxoAR2sW1GQXTiuT2iHE+iGnXgJx1lu9sUWJPnlMqRO8/5Y5qknpb5QTtLCfKKNogs+mZ8agRBxZRNE2tC4kN9P4nxn8Kq+PGYsIZSH/eG80OR2kzXwpxa11tPYmxX/0b9pwqGGlfpYJdimzVC0wo2cGYHAIbfeCCk=
